cask "atom"
cask "visual-studio-code"
cask "intellij-idea-ce"
brew "jenv"
brew "rbenv"
brew "yarn"
brew "cookiecutter"
tap "caskroom/versions"
cask "java8"
cask "drawio"

# Development
brew "llvm"
brew "gcc", args: ["without-multilib"]

# Parallel processing
brew "libomp"

cask "devdocs"
