# Taps
tap "homebrew/cask-versions"
tap "grpc/grpc"

brew "jenv"
brew "rbenv"
brew "pyenv"
brew "nvm"
brew "yarn"
brew "cookiecutter"

# Development
brew "llvm"
brew "gcc", args: ["without-multilib"]
brew "grpc", args: ["with-plugins"]
brew "go", args: ["cross-compile-common"]

# Parallel processing
brew "libomp"


cask "java8"
#cask "drawio"


#cask "devdocs"
