tap "caskroom/fonts"
cask "font-fira-code"
cask "font-firacode-nerd-font"

# Cursive font Script 12 BT
cask "./font-script12-bt.rb"

brew "rlwrap"
brew "wget"
brew "libssh2"
brew "p7zip"
brew "libxml2"  # Required for tidyverse
brew "jq"

# Mac app store command line
brew "mas"

# Chrome Browser
cask "google-chrome"
